version: '3.8'
services:
  db:
    image: postgres:16
    container_name: stock-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retail_stock
    ports:
      - "5433:5432"